/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Marcel van Duijn (https://sketchfab.com/MarcelvanDuijn)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/neonroad-endless-loop-425480c926144a3395b9cc8f672a8db4
title: NeonRoad endless loop
*/
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // actions['Road|MovingAction'].play();
    // actions['BackGround|MovingAction'].play();
    // actions['CenterLine|MovingAction'].play();
    // actions['Enviroment|MovingAction'].play();
    // actions['Shade1|MovingAction'].play();
    // actions['Shade2|MovingAction'].play();
    // actions['Shade3|MovingAction'].play();
    // actions['SideSideLeft|MovingAction'].play();
    // actions['Camera|MovingAction'].play();
    actions['Moving|MovingAction'].play();





    actions['Moving|MovingAction'].setEffectiveTimeScale(props.mouse);

  })





  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Camera"
            position={[0, 367.53, 3844.84]}
            rotation={[-0.04, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          />
          <group name="Moving" position={[0, 0, 3966.67]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <group name="Enviroment" scale={[13, 30, 13.98]}>
              <mesh
                geometry={nodes.Enviroment_Material001_0.geometry}
                material={nodes.Enviroment_Material001_0.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material001_0_1.geometry}
                material={nodes.Enviroment_Material001_0_1.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0.geometry}
                material={nodes.Enviroment_Material002_0.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_1.geometry}
                material={nodes.Enviroment_Material002_0_1.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_2.geometry}
                material={nodes.Enviroment_Material002_0_2.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_3.geometry}
                material={nodes.Enviroment_Material002_0_3.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_4.geometry}
                material={nodes.Enviroment_Material002_0_4.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_5.geometry}
                material={nodes.Enviroment_Material002_0_5.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_6.geometry}
                material={nodes.Enviroment_Material002_0_6.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_7.geometry}
                material={nodes.Enviroment_Material002_0_7.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_8.geometry}
                material={nodes.Enviroment_Material002_0_8.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_9.geometry}
                material={nodes.Enviroment_Material002_0_9.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_10.geometry}
                material={nodes.Enviroment_Material002_0_10.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_11.geometry}
                material={nodes.Enviroment_Material002_0_11.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_12.geometry}
                material={nodes.Enviroment_Material002_0_12.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_13.geometry}
                material={nodes.Enviroment_Material002_0_13.material}
              />
              <mesh
                geometry={nodes.Enviroment_Material002_0_14.geometry}
                material={nodes.Enviroment_Material002_0_14.material}
              />
            </group>
            <group name="Road" position={[0, 0, 0.09]} scale={[2.98, 30, 2.98]}>
              <group name="CenterLine" position={[0, 0, 0.01]} scale={[0.03, 0.1, 0.06]}>
                <mesh geometry={nodes.CenterLine_Material007_0.geometry} material={materials['Material.007']} />
              </group>
              <group name="SideRight" position={[1.02, 0, 0.01]} rotation={[-Math.PI, 0, 0]} scale={[-0.02, -1, -1]}>
                <mesh
                  geometry={nodes.SideRight_Material006_0.geometry}
                  material={nodes.SideRight_Material006_0.material}
                />
              </group>
              <group
                name="SideSideLeft"
                position={[-1.02, 0, 0.01]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-0.02, -1, -1]}>
                <mesh
                  geometry={nodes.SideSideLeft_Material006_0.geometry}
                  material={nodes.SideSideLeft_Material006_0.material}
                />
              </group>
              <mesh geometry={nodes.Road_Material005_0.geometry} material={materials['Material.005']} />
            </group>
            <group position={[-7.71, 0, 0]} scale={[0.6, 0.6, 0.6]}>
              <group position={[1.94, 0, 14.65]} rotation={[0, 0, 0]} scale={[0.57, 0.57, 0.57]}>
                <mesh
                  geometry={nodes.PalmTreeTopLeft_Material_0.geometry}
                  material={nodes.PalmTreeTopLeft_Material_0.material}
                />
                <mesh
                  geometry={nodes.PalmTreeTopLeft_Material008_0.geometry}
                  material={nodes.PalmTreeTopLeft_Material008_0.material}
                />
                <mesh
                  geometry={nodes.PalmTreeTopLeft_Material008_0_1.geometry}
                  material={nodes.PalmTreeTopLeft_Material008_0_1.material}
                />
              </group>
              <mesh
                geometry={nodes.PalmTree_Left_Material009_0.geometry}
                material={nodes.PalmTree_Left_Material009_0.material}
              />
              <mesh
                geometry={nodes.PalmTree_Left_Material010_0.geometry}
                material={nodes.PalmTree_Left_Material010_0.material}
              />
            </group>
            <group position={[7.24, 0, 0]} scale={[0.6, 0.6, 0.6]}>
              <group position={[1.94, 0, 14.65]} rotation={[0, 0, 0]} scale={[0.57, 0.57, 0.57]}>
                <mesh
                  geometry={nodes.PalmTreeTopLeft001_Material_0.geometry}
                  material={nodes.PalmTreeTopLeft001_Material_0.material}
                />
                <mesh
                  geometry={nodes.PalmTreeTopLeft001_Material008_0.geometry}
                  material={nodes.PalmTreeTopLeft001_Material008_0.material}
                />
                <mesh
                  geometry={nodes.PalmTreeTopLeft001_Material008_0_1.geometry}
                  material={nodes.PalmTreeTopLeft001_Material008_0_1.material}
                />
              </group>
              <mesh
                geometry={nodes.PalmTree_Left001_Material009_0.geometry}
                material={nodes.PalmTree_Left001_Material009_0.material}
              />
              <mesh
                geometry={nodes.PalmTree_Left001_Material010_0.geometry}
                material={nodes.PalmTree_Left001_Material010_0.material}
              />
            </group>
          </group>
          {/* <group
            name="BackGround"
            position={[681.53, 1870.56, -50454.77]}
            rotation={[0, 0, 0]}
            scale={[-49897.68, -50362.87, -8644.26]}>
            <mesh
              geometry={nodes.BackGround_Material004_0.geometry}
              material={nodes.BackGround_Material004_0.material}
            />
          </group> */}
          <group position={[103.81, 0, -44959.13]} rotation={[-Math.PI / 2, 0, 0]} scale={[3586.33, 3586.33, 3586.33]}>
            <group
              name="Shade1"
              position={[-0.03, -1.04, 0.06]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-1.04, -0.02, -0.18]}>

              <mesh geometry={nodes.Shade1_Material004_0.geometry} material={nodes.Shade1_Material004_0.material} />
            </group>
            <group
              name="Shade2"
              position={[-0.03, -1.04, 0.14]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-1.04, -0.03, -0.18]}>
              <mesh geometry={nodes.Shade2_Material004_0.geometry} material={nodes.Shade2_Material004_0.material} />
            </group>
            <group
              name="Shade3"
              position={[-0.03, -1.02, 0.24]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-1.04, -0.05, -0.18]}>
              <mesh geometry={nodes.Shade3_Material004_0.geometry} material={nodes.Shade3_Material004_0.material} />
            </group>
            <mesh geometry={nodes.Sun_Material003_0.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../scene.gltf')
